# Generated by Django 2.2.2 on 2020-07-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_station_station_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='station_used',
            new_name='station_Status',
        ),
    ]
