# Generated by Django 2.2.2 on 2020-07-20 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_station_station_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
